version: '3'

services:
  sesinetd:
    container_name: sesinetd
    hostname: sesinetd
    build:
      context: .
      dockerfile: Dockerfile
    image: houdini:18.5
    ports:
      - 1715:1715
    environment:
      - SIDEFX_USER=${SIDEFX_USER}
      - SIDEFX_PW=${SIDEFX_PW}
